// 오프라인에서도 쓸 수 있는 여행 필수 회화 (미리 번역됨)
window.PHRASES = {
  '기본': [
    ['안녕하세요', 'Hello.'],
    ['감사합니다', 'Thank you.'],
    ['죄송합니다', "I'm sorry."],
    ['실례합니다', 'Excuse me.'],
    ['천천히 말씀해 주세요', 'Could you speak more slowly, please?'],
    ['다시 한 번 말씀해 주세요', 'Could you say that again, please?'],
    ['영어를 잘 못해요', "I don't speak English very well."],
    ['여기에 적어 주시겠어요?', 'Could you write it down here?'],
  ],
  '공항·호텔': [
    ['체크인하고 싶어요', "I'd like to check in, please."],
    ['예약했어요. 이름은 ○○입니다', 'I have a reservation under the name ○○.'],
    ['체크아웃은 몇 시예요?', 'What time is check-out?'],
    ['짐을 맡길 수 있나요?', 'Can I leave my luggage here?'],
    ['와이파이 비밀번호가 뭐예요?', 'What is the Wi-Fi password?'],
    ['방에 수건이 더 필요해요', 'I need more towels in my room.'],
    ['제 짐이 안 나왔어요', "My luggage didn't arrive."],
    ['환승은 어디서 하나요?', 'Where do I go for my connecting flight?'],
  ],
  '교통·길찾기': [
    ['이 주소로 가 주세요', 'Please take me to this address.'],
    ['역이 어디에 있나요?', 'Where is the station?'],
    ['여기서 걸어갈 수 있나요?', 'Can I walk there from here?'],
    ['얼마나 걸리나요?', 'How long does it take?'],
    ['이 버스 ○○에 가나요?', 'Does this bus go to ○○?'],
    ['표는 어디서 사나요?', 'Where can I buy a ticket?'],
    ['여기서 내려 주세요', 'Please drop me off here.'],
    ['길을 잃었어요', "I'm lost."],
  ],
  '식당': [
    ['두 명 자리 있나요?', 'Do you have a table for two?'],
    ['메뉴판 좀 주세요', 'Could I see the menu, please?'],
    ['추천 메뉴가 뭐예요?', 'What do you recommend?'],
    ['이걸로 주세요', "I'll have this, please."],
    ['맵지 않게 해 주세요', 'Please make it not spicy.'],
    ['땅콩 알레르기가 있어요', "I'm allergic to peanuts."],
    ['물 좀 주세요', 'Could I have some water, please?'],
    ['계산서 주세요', 'Could I have the check, please?'],
    ['포장해 주세요', 'Can I get this to go?'],
  ],
  '쇼핑': [
    ['이거 얼마예요?', 'How much is this?'],
    ['좀 깎아 주실 수 있나요?', 'Could you give me a discount?'],
    ['카드 되나요?', 'Do you accept credit cards?'],
    ['다른 사이즈 있나요?', 'Do you have this in another size?'],
    ['입어 봐도 되나요?', 'Can I try this on?'],
    ['그냥 둘러보는 중이에요', "I'm just looking."],
    ['면세 되나요?', 'Can I get a tax refund?'],
    ['영수증 주세요', 'Could I have a receipt, please?'],
  ],
  '긴급': [
    ['도와주세요!', 'Help!'],
    ['경찰을 불러 주세요', 'Please call the police.'],
    ['구급차를 불러 주세요', 'Please call an ambulance.'],
    ['병원이 어디예요?', 'Where is the hospital?'],
    ['약국이 어디예요?', 'Where is the pharmacy?'],
    ['여권을 잃어버렸어요', "I lost my passport."],
    ['지갑을 도둑맞았어요', 'My wallet was stolen.'],
    ['여기가 아파요', 'It hurts here.'],
    ['한국 대사관에 연락해 주세요', 'Please contact the Korean embassy.'],
  ],
};
